### ISSUE TITLE
划分树性价比感觉不如函数式线段树啊……

### ISSUE THREAD

**Issue by zjyjer** [jinzhao1994/template_2016#1]

**Comment by jinzhao1994** [comment]
函数式线段树感觉不需要模板的样子...跟普通线段树没啥区别啊..

**Comment by zjyjer** [comment]
那划分树更没什么必要了吧……

**Comment by jinzhao1994** [comment]
不..是因为函数式线段树手写起来很简单啊...划分树我写不出来呀...

**Comment by zjyjer** [comment]
= =||| 你是说会遇到问题只能用划分树做而不能用函数式线段树吗？

**Comment by jinzhao1994** [comment]
的确有我不会的？单纯查询区间第k大，函数式线段树不是俩log么...

**Comment by zjyjer** [comment]
你冷静一下……
无修改的区间第K大 显然是一个log的好伐？

**Comment by jinzhao1994** [comment]
咦，看来我的做法一直不对啊...不是二分答案么

**Comment by zjyjer** [comment]
不用二分答案啊……
直接从线段树的根往下走一遍就好了
https://gist.github.com/zjyjer/bdc7f5b4e8efc0df352bd4e853a5ab40

**Comment by jinzhao1994** [comment]
诶...你说得好有道理啊...这么说来划分树好废啊..

**Comment by zjyjer** [comment]
我简直要觉得你是来钓鱼的……
